# Generated by Django 5.2.1 on 2025-05-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='likeur',
        ),
    ]
